# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842a24e1f7f7e6dae1ba91e2fe33c196ba32933327d97cf468e80a4bac9964ce486c486f509c3af02b026b1d7437928b78c9067200f0ac005f171f1aadb73b9b

test:
  secret_key_base: 8f386848e68b88c6def6f4c4b3e72bae05a7d322ac408e38d207c405c33ecee9c1127adaa0a19422466d0adf25067e1c70a37a1548bd8eed5d6f426fc549a9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
